apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argocd-applications/argocd.yaml
- argocd-applications/argo-rollouts.yaml
- argocd-applications/cert-manager.yaml
- argocd-applications/istio-ingress.yaml
- argocd-applications/istio.yaml
- argocd-applications/gateway-api.yaml

